### ISSUE TITLE
The Social icons on the Hero section doesn't have a margin bottom on screen sizes with minimum width of 768px

### ISSUE THREAD

**Issue by uzoway** [Lyannah-LLC/Lyannah#1]
# Describe the issue
The three `Social` icons(discord, twitter and github) on the `Hero` section doesn't have margin around them which doesn't look good for the user interface of Lyannah waiting list website. This is only applicable to screens with minimum width of 768px. The icons appears to have adequate margin on screens below 768px.

# Affected Page
This only affects the Landing page of the waiting list website as the `Social` icon component was only used there.

# Expected behaviour
The div inside the `Social` component should have a margin-bottom of 1rem for screen sizes with min-width:768px like this `md:mb-4`

```js
<div  className={`${classes.social} px-5 md:mb-4 py-2 text-sm md:inline-flex flex items-center rounded-xl md:mr-5 md:mb-0 mb-5 delay-75 cursor-pointer`} onClick={prop.onClick}>
```

# Current behaviour
The div inside the `Social` component doesn't have margin for screen sizes with minimum screen size of 768px which makes the icons look broken.

```js
<div  className={`${classes.social} px-5  py-2 text-sm md:inline-flex flex items-center rounded-xl md:mr-5 md:mb-0 mb-5 delay-75 cursor-pointer`} onClick={prop.onClick}>
```

# Steps to reproduce the bug
1. Start the project on your computer
`npm install`
`npm start`
2. Open http://localhost:3000/ to view it in the browser
3. Observe the three social icons(discord, twitter and github) on the hero section on the website
 
# Context
- Device: Desktop
- OS: Windows 11
- Browser: Google Chrome
- Version: 102.0.5005.115

I'm bringing this up because I thought a fix to the bug will give the waiting list page a better look since for now it is a first point of contact for anyone who is trying to learn about Lyannah.

**Comment by fiizzy** [comment]
Nice catch!
I was able to reproduce the error on my end.
I have fixed it and gone ahead to close the issue

**Comment by uzoway** [comment]
That's great. Thank you!
