### ISSUE TITLE
Auth pages: Design rearangement

### ISSUE THREAD

**Issue by godwin-morwin** [Lyannah-LLC/Lyannah#5]
The Figma design is different from what was coded out. so I am trying to correct that and make necessary adjustments
![Screen Shot 2022-06-27 at 6 24 22 PM](https://user-images.githubusercontent.com/54848535/176000116-7e7b2223-937d-4e3f-be6e-b7f8316bda16.png)
![Screen Shot 2022-06-27 at 6 25 27 PM](https://user-images.githubusercontent.com/54848535/176000234-3bba7b6e-8810-49f9-8c5d-8cc1fe56d475.png)

**Comment by fiizzy** [comment]
Great!
What are some of the inconsistencies that you notice?

Could you list them out in a bullet point? Some designs might have deliberately been changed.

**Comment by godwin-morwin** [comment]
> 

* The spacing between the ( Logo name ) and the (let's get you in ) sub header is not the same as the Figma design

* The GitHub and icon and the ( signup with Github ) is not aligned properly. same with the Google section as well.

* The ( OR ) is not centered according to the design

* The size of the Form container is bigger than the exact size, in Figma. and that's causing the intro text beside the form to not have enough breathing space as given in the design

* I also noticed the font size is too small.  i checked using the console and found out the size is different 

* Also , the input fields are not validated yet

* Forgot password link is not where its supposed to be placed

**Comment by godwin-morwin** [comment]
Don't mind my expertise. have just been thought to always work with and according to design

**Comment by fiizzy** [comment]
Okay, very nice. They are pretty valid issues that could be fixed! 
Nice catch 🔥

Looking forward to the PR!
